# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mishmanners
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

Step 3. Running GitHub Actions

Once you've added the code above and committed it, head to your Actions tab. Under "Workflows", you should see the "Generate Snake" Action you created above.

Workflow

Click "Run Workflow" and watch your workflow run. You can even expand your workflow and see what's happening in real time.

Running Actions

Once your workflow has finished running, you should have received a green ‚úÖ "build" checkmark. If so, this means your Action is working nicely. If not, you'll have to go through the code and see where the errors are. The "build" status should give you some indication of where your errors lie. You can also compare it with the yaml file on my GitHub Profile README.

Build green

If you have the green "build" ‚úÖ then you should be good to go. Head back to your repo's "Code" directory, and change your branch to "output". Here you'll find the two versions of your contribution graph with the snake eating it: a *.gif and a *.svg. The good thing about these files is the file is rewritten over itself every time the Action runs. Thus, your contribution graph will always be up to date.

CodeOutput
Step 4. Adding a contribution-eating snake to your profile

Now the final set is to add this to your profile. Grab the file location of your *.gif. It should be something like:

https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif

Add this to your profile by copying the file location onto a new line in your markdown file:

![snake gif](https://github.com/YOUR_USERNAME/YOUR_USERNAME/blob/output/github-contribution-grid-snake.gif)

Now you should have a really cool looking snake eating your contributions!

SnakeEating

Hopefully this guide was helpful for you and gives you a good base to start building and adding more Actions on your profile. What have you been adding to your GitHub Profile README? Other there other cool Actions I should be looking at?
GitHub Like a Boss (23 Part Series)
1 GitHub Desktop for better repo organisation
2 GitHub README for easy to understand code
... 19 more parts...
22 How to automatically close your issues once you merge a PR
23 How to get more suggestions from GitHub Copilot
Top comments (39)
pic
 
kushaltanna24 profile image
‚Ä¢
Jun 3 '22

Work fine.! Here is mine - KushalTanna24
Reply
 
msoftware profile image
‚Ä¢
Jul 9 '21

Great tutorial! Works for me.
Here's mine - github.com/msoftware
Reply
 
gustavohgmartins profile image
‚Ä¢
Sep 3 '21

Awsome! How did you change the background-color?
Reply
 
mishmanners profile image
‚Ä¢
Sep 3 '21

I didn't change the background colour. It's a .png/.svg image, meaning the background is transparent. It looks dark on mine because I have dark mode enabled on GitHub. You can enable it by clicking Settings --> Appearance --> choosing your mode.
Thread
 
gustavohgmartins profile image
‚Ä¢
Sep 3 '21

Thank you! actually I was using the .gif version, so I switched to the .svg one and voil√°
Thread
 
mishmanners profile image
‚Ä¢
Sep 3 '21

Awesome! Glad to be of help üòÑ
Reply
 
baayah profile image
‚Ä¢
Jan 11

Thank you so much! I tried to change in settings 'Contribution' to 'include my private contributions' but anyway my Readme profile doesn't show My Contributions. Could you please help me with this?
github.com/BAayah/BAayah
Reply
 
l3on06 profile image
‚Ä¢
Feb 17 '23

Hello everyone, before proceeding, please navigate to 'Settings -> Actions -> General -> Workflow Permissions' in your README.md file and select 'Read and Write' permissions. This is important because if you have other permissions selected, it may result in errors.
Reply
 
jakon62508112 profile image
‚Ä¢
Jan 21 '23 ‚Ä¢ Edited on Jan 21

Getting this error when I try to run workflow and after it fails:
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Reply
 
shuvajitgeek profile image
‚Ä¢
Feb 2 '23

go to setting -> action -> and check the workflow as read and write
(run build again) hopefully you will not get error
Reply
 
ariafatah profile image
‚Ä¢
Sep 18 '23

github.com/ariafatah0711/ariafatah...

Check my github and change this file because I tried the file above only as much as it appears if you want to use the full one I use. And don't forget to give starsüòÅ
Reply
 
ariafatah profile image
‚Ä¢
Sep 18 '23

If the action fails, you can go to repo settings, click action, then select general, and look at the bottom where it says read and write.
Reply
 
hoangtien_2k3 profile image
‚Ä¢
Jan 29 '23 ‚Ä¢ Edited on Jan 29

It does not work for me. Can someone help me?
github.com/hoangtien2k3qx1

Error:
actions/checkout@v2, platane/snk@master, ad-m/github-push-action@master, and crazy-max/ghaction-github-pages@v2.1.3 are not allowed to be used in hoangtien2k3qx1/hoangtien2k3qx1. Actions in this workflow must be: within a repository owned by hoangtien2k3qx1.
Reply
 
bpolaswar profile image
‚Ä¢
Oct 17 '21

Great worked for me. See github.com/bpolaswar
Thanks.
Reply
 
wkylin profile image
‚Ä¢
May 1 '22

Here's mine:
github.com/wkylin
Reply
 
hudsonpufferfish profile image
‚Ä¢
Jan 8 '23

I got error "The process '/usr/bin/git' failed with exit code 128". Even though I tried to generate a new personal access token, it didn't work. Anybody has any solution for this error?
Reply
 
nirav97120 profile image
‚Ä¢
Dec 16 '22

Awesome My github profile
Reply
 
adityamangal1 profile image
‚Ä¢
Jul 22 '21

Awesome Tutorial! üêç
Reply
 
viveeeeeek profile image
‚Ä¢
Oct 3 '21

Awesome!
Reply
 
zieldecastro profile image
‚Ä¢
Sep 15 '21 ‚Ä¢ Edited on Sep 15

It does not work for me. Can someone help me?
github.com/zieldecastro
instagram.com/zieldecastro/
Reply
 
shasank27 profile image
‚Ä¢
Aug 8 '21 ‚Ä¢ Edited on Aug 8

Great tutorial!
But can anyone help me, its not showing all my contributions
github.com/shasank27/shasank27
Reply
 
mishmanners profile image
‚Ä¢
Sep 6 '21 ‚Ä¢ Edited on Sep 6

Hey Shasank. I can't see it on your profile, but to show all contributions, you need to make sure all contributions are turned on your profile. You can do this in your settings:

github.com/YOUR_PROFILE --> Settings --> Profile

Then scroll down to "Contributions" and check the box that says "Include private contributions on my profile".

Hope that helps.
Reply
View full discussion (39 comments)
Code of Conduct ‚Ä¢ Report abuse
profile
Arm
Promoted

Image of Arm event
Learn How Ruth Amos Supercharges Developer Creativity

üßíüèΩ Tap into your child-inspired creativity.
ü§ù Embrace fearless problem-solving.
üí° Create ground-breaking solutions.
üîë Level up your design and development skills.
üèÜ Learn from an award-winning engineer and innovator.

Register Now
Read next
afrozansenjuti profile image
Handling External JS Files in a React Website

Afroza Nowshin - Feb 4
nguhprince profile image
Flask tutorial: A student project recorder

Prince - Jan 22
ourabigdev profile image
My First Impressions of Odin Programming Language for Game Development

hatim oura - Feb 4
akashpattnaik profile image
Notifications in flutter

Akash Pattnaik - Feb 12
Michelle Mannering
Developer Advocate | Hackathon Queen | International Speaker

    Location
    Australia
    Education
    The University of Melbourne
    Work
    Developer Advocate at GitHub
    Joined
    May 29, 2020

More from Michelle Mannering
Support the projects you rely on: GitHub Sponsors
#github #opensource #career
The GitHub Community Roundup - 2024.02.23
#github #developer #news #community
The GitHub Community Roundup - 2024.02.16
#github #community #news #developer
profile
Sentry
Promoted

Sentry Launch Week
Calling all devs! Sentry Launch Week is coming.

Tune in March 18-22nd for new products, demos, and discussions with experts from the community.

Tune In


# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: KuzeNoYagami
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
